### PR TITLE
Fix a bug when using a custom exception with a custom exception message. Also remove tests for Python 3.2 and 3.3.

### LINKED ISSUE #54: Error when specifying a different exception type with an exception message.
https://github.com/pnpnpn/timeout-decorator/blob/3ad0308d30c4904b9ea272da326c0c3795161378/timeout_decorator/timeout_decorator.py#L47

As far as I can tell, this decorator does not work when passing a normal exception (RuntimeError, IOError, or base Exception) and an exception message. This occurs because the base exception class and the others I mentioned do not accept the 'value' argument. Instead, trying to call a RuntimeError with the value keyword throws a TypeError exception.

See below.

Python 2.7.13 (default, Nov 24 2017, 17:33:09) 
>>> raise Exception(value='My Message.')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: exceptions.Exception does not take keyword arguments

I will try to submit a pull request, but note that I believe a one line change solves this.

Change
  raise exception(value=exception_message)
to 
  raise exception(exception_message)

This works with the builtin TimeoutError class as well, where the value keyword was added, since TimeoutError only has one keyword argument.

### PR DESCRIPTION
**Pull request by tlalexander**
Fixes #54 

Test included. I didn't see how to run the test so hopefully it just passes. :)

### CODE REVIEW

**Comment by tlalexander** [comment]
Hmmm. I fixed the linter error And most of the tests pass now. The tests that fail seem to be failing due to the python version used for those tests, which doesn't seem to be caused by my code. So I think it's good now? I'm new to this system.

**Comment by tlalexander** [comment]
It looks like tox no longer supports python 3.2 and 3.3, so I've removed those from the tests.

I base my understanding on the comment "tox fails (because setuptools has dropped support for Python 3.3 since v40.0.0)." From this page:
https://github.com/noahmorrison/chevron/issues/42

Well... The test just completed as I was writing this comment, and it seems I failed to disable the tests in the way I had intended. I will try to see what I can do here, but perhaps this needs to be fixed by the project owner...

**Comment by tlalexander** [comment]
Okay! Sorry I missed the .travis.yml as I was only looking in the command line with "ls" and the yml was hidden. Got it sorted! It does look like the tests for python 3.2 and 3.3 should be removed. Hopefully my changes look good.

Thanks!

**Comment by pnpnpn** [comment]
lgtm. Can you please bump the version to `0.4.1`? See https://github.com/pnpnpn/timeout-decorator/commit/2bc336d6ed08eb380f51d249ac33a3d284ae10f4

**Comment by tlalexander** [comment]
Done. Thanks for the quick response!

**Pull request merged**
